//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DownMarker.Core.Properties
{


   /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DownMarker.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example Markdown Document
        ///=========================
        ///
        ///The Basics
        ///----------
        ///
        ///Hello world! 
        ///
        ///A new paragraph. Now we force a new line within the paragraph by putting two spaces at the end:  
        ///New line.
        ///
        ///We can put *emphasis* or **strong emphasis** on something.
        ///
        ///
        ///A list:
        ///
        /// - red
        /// - blue
        /// - green
        ///
        ///A quote:
        ///
        ///&gt; What&apos;s in a name? that which we call a rose  
        ///&gt; By any other name would smell as sweet;
        ///
        ///A link to [google](http://www.google.com).
        ///You can also have automatic links where the target is the same as the des [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string markdownhelp {
            get {
                return ResourceManager.GetString("markdownhelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Started
        ///===========
        ///
        ///[Create New Document](downmarker:new)  
        ///[Open Existing Document](downmarker:open)  
        ///[Example Markdown Document](downmarker:example)
        ///
        ///Recently Opened Files:
        ///----------------------
        ///
        ///%recentlyused%
        ///.
        /// </summary>
        internal static string startpageTemplate {
            get {
                return ResourceManager.GetString("startpageTemplate", resourceCulture);
            }
        }
    }
}
